### ISSUE TITLE
Cannot close all files in mu-editor on iMac

### ISSUE THREAD

**Issue by marcovanurk** [mu-editor/mu#594] opened 2018-07-30 09:28 UTC
If I open mu-editor on my iMac, it always opens with the last script I edited. And I can't close that script. It sticks there 'forever'. If I open more scripts using 'New'. I can't even close that other script.

If I close mu-editor with more than one script. And open mu-editor again, all the scripts are there. I can close them all, but one.

The only workaround is, after closing mu-editor, to delete the file 'session.json' in 'Library/Application support/mu'.

**Comment by marcovanurk** [comment] 2018-07-30 10:31
No it is not the far left tab. If I open a new one. And make that the most left one, I can delete this one.

Rearranging does not effect this. If I rearrange, I could not delete the one who came during opening mu-editor. It is since the last version; I use mu 1.0.0. The one before this one did not had this problem; as far as I can remember.

**Comment by marcovanurk** [comment] 2018-07-30 10:37
By the way, to be complete: it is when using mu-editor in 'BBC micro:bit' mode.

**Comment by ZanderBrown** [comment] 2018-07-30 11:23
So it's the tab that started on the left? Very weird.

This defo feels like a Qt bug, @carlosperate can you replicate this?

**Comment by jamesabela** [comment] 2018-08-04 10:53
Yes, I have the same problem on my Mac.  The script to the far left refuses to go away even when I have other tabs.
![image](https://user-images.githubusercontent.com/16495873/43675746-8c9f80aa-9817-11e8-8eec-7b6db34beeed.png)

**Comment by carlosperate** [comment] 2018-08-07 15:10
I can confirm the issue on macOS. Even if the tab is moved around the other tabs the left close button doesn't seem to work.

**Comment by ZanderBrown** [comment] 2018-08-07 15:48
@carlosperate  it shouldn't be on the left anyway

https://github.com/mu-editor/mu/blob/bd722c72f63bd0d6f51847e82852bf0638c22002/mu/resources/css/day.css#L62-L66

Quick fix would be remove L65 and have macOS show close button on the left, not necessarily ideal but should work. Can't find a QTBUG for this.

**Comment by carlosperate** [comment] 2018-08-08 13:59
@ZanderBrown is it safe assumption that this is a QT bug, instead of a PyQt5 one? The assumption being that the CSS is process directly by QT, bypassing anything that PyQt5 wrapper might do?

If so, perhaps the most time-consuming task to open an issue would be to create a minimum example. Do you know if the QT tracker takes bugs reported with the Python bindings?
If we have to write a few lines of Python, maybe it would be more productive to do that in PySide2 since it is now the official Python bindings from QT?

Nevertheless, even if this is a QT bug, going through the process of reporting it, getting a fix merged, waiting for the next QT release, and then the next PyQt5 release, all will likely to take several months.
From my point of view, we should probably try to find a workaround, or as Zander has suggested, remove the fixed button position, as having this discrepancy between platforms is a lesser evil.

**Comment by ZanderBrown** [comment] 2018-08-08 16:13
@carlosperate Yes it seems highly unlikely PyQt has anything to do with this, last time I opened a QTBUG I submitted a C++ "Qt Creator" project (not that I've had much response for that)

**Comment by murilopolese** [comment] 2018-09-10 12:27
I also confirm this behavior. Can't close that tab D:

**Comment by ntoll** [comment] 2018-09-29 20:00
Fixed by #619

**Closed by ntoll** 2018-09-29 20:00 UTC
