### ISSUE TITLE
mac pgzero

### ISSUE THREAD

**Issue by illume** [mu-editor/mu#349] opened 2018-02-21 19:49 UTC
Exhaustive details here. 
https://bitbucket.org/lordmauve/pgzero/issues/63

Is it supposed to be calling `pgzrun`?

**Comment by ukBaz** [comment] 2018-02-21 21:39
I am seeing a similar issue. These are the steps I followed.

I created a venv to install mu:
```linux
eddies-computer:~ barry$ python3 -m venv venvs/mu_beta
eddies-computer:~ barry$ cd venvs/mu_beta/
eddies-computer:mu_beta barry$ ll
total 8
drwxr-xr-x   6 barry  502   204B 21 Feb 20:56 .
drwxr-xr-x   3 barry  502   102B 21 Feb 20:56 ..
drwxr-xr-x  12 barry  502   408B 21 Feb 20:57 bin
drwxr-xr-x   2 barry  502    68B 21 Feb 20:56 include
drwxr-xr-x   3 barry  502   102B 21 Feb 20:56 lib
-rw-r--r--   1 barry  502   114B 21 Feb 20:56 pyvenv.cfg
eddies-computer:mu_beta barry$ source bin/activate
(mu_beta) eddies-computer:mu_beta barry$ pip install mu-editor
Collecting mu-editor
  Downloading mu_editor-1.0.0b15-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.6MB 401kB/s 
Collecting pyserial==3.4 (from mu-editor)
  Using cached pyserial-3.4-py2.py3-none-any.whl
Collecting PyQtChart==5.10 (from mu-editor)
  Downloading PyQtChart-5.10-5.10.0-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl (771kB)
    100% |████████████████████████████████| 778kB 301kB/s 
Collecting pgzero==1.1 (from mu-editor)
  Downloading pgzero-1.1.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 472kB/s 
Collecting pycodestyle==2.3.1 (from mu-editor)
  Downloading pycodestyle-2.3.1-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 570kB/s 
Collecting qtconsole==4.3.1 (from mu-editor)
  Downloading qtconsole-4.3.1-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 903kB/s 
Collecting pyqt5==5.10 (from mu-editor)
  Downloading PyQt5-5.10-5.10.0-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl (86.1MB)
    100% |████████████████████████████████| 86.1MB 13kB/s 
Collecting qscintilla==2.10.2 (from mu-editor)
  Downloading QScintilla-2.10.2-5.9.3-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 418kB/s 
Collecting matplotlib==2.1.2 (from mu-editor)
  Downloading matplotlib-2.1.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.2MB)
    100% |████████████████████████████████| 13.2MB 92kB/s 
Collecting pyflakes==1.6.0 (from mu-editor)
  Downloading pyflakes-1.6.0-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 665kB/s 
Collecting pygame>=1.9 (from pgzero==1.1->mu-editor)
  Downloading pygame-1.9.3-cp36-cp36m-macosx_10_9_intel.whl (4.8MB)
    100% |████████████████████████████████| 4.8MB 212kB/s 
Collecting ipython-genutils (from qtconsole==4.3.1->mu-editor)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting jupyter-client>=4.1 (from qtconsole==4.3.1->mu-editor)
  Downloading jupyter_client-5.2.2-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 851kB/s 
Collecting ipykernel>=4.1 (from qtconsole==4.3.1->mu-editor)
  Downloading ipykernel-4.8.2-py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 883kB/s 
Collecting pygments (from qtconsole==4.3.1->mu-editor)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 397kB/s 
Collecting traitlets (from qtconsole==4.3.1->mu-editor)
  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 639kB/s 
Collecting jupyter-core (from qtconsole==4.3.1->mu-editor)
  Downloading jupyter_core-4.4.0-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 701kB/s 
Collecting sip<4.20,>=4.19.4 (from pyqt5==5.10->mu-editor)
  Downloading sip-4.19.7-cp36-cp36m-macosx_10_6_intel.whl (51kB)
    100% |████████████████████████████████| 51kB 1.2MB/s 
Collecting six>=1.10 (from matplotlib==2.1.2->mu-editor)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting numpy>=1.7.1 (from matplotlib==2.1.2->mu-editor)
  Downloading numpy-1.14.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.7MB)
    100% |████████████████████████████████| 4.7MB 228kB/s 
Collecting cycler>=0.10 (from matplotlib==2.1.2->mu-editor)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib==2.1.2->mu-editor)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 822kB/s 
Collecting python-dateutil>=2.1 (from matplotlib==2.1.2->mu-editor)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 784kB/s 
Collecting pytz (from matplotlib==2.1.2->mu-editor)
  Downloading pytz-2018.3-py2.py3-none-any.whl (509kB)
    100% |████████████████████████████████| 512kB 644kB/s 
Collecting tornado>=4.1 (from jupyter-client>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading tornado-4.5.3.tar.gz (484kB)
    100% |████████████████████████████████| 491kB 561kB/s 
Collecting pyzmq>=13 (from jupyter-client>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading pyzmq-17.0.0-cp36-cp36m-macosx_10_6_intel.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 476kB/s 
Collecting ipython>=4.0.0 (from ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading ipython-6.2.1-py3-none-any.whl (745kB)
    100% |████████████████████████████████| 747kB 485kB/s 
Collecting decorator (from traitlets->qtconsole==4.3.1->mu-editor)
  Downloading decorator-4.2.1-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading pexpect-4.4.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 1.4MB/s 
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading prompt_toolkit-1.0.15-py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 864kB/s 
Requirement already satisfied: setuptools>=18.5 in ./lib/python3.6/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
Collecting appnope; sys_platform == "darwin" (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading appnope-0.1.0-py2.py3-none-any.whl
Collecting pickleshare (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading simplegeneric-0.8.1.zip
Collecting jedi>=0.10 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading jedi-0.11.1-py2.py3-none-any.whl (250kB)
    100% |████████████████████████████████| 256kB 851kB/s 
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading ptyprocess-0.5.2-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Collecting parso==0.1.1 (from jedi>=0.10->ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Downloading parso-0.1.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 789kB/s 
Installing collected packages: pyserial, sip, pyqt5, PyQtChart, pygame, pgzero, pycodestyle, ipython-genutils, tornado, decorator, six, traitlets, python-dateutil, jupyter-core, pyzmq, jupyter-client, ptyprocess, pexpect, wcwidth, prompt-toolkit, appnope, pickleshare, pygments, simplegeneric, parso, jedi, ipython, ipykernel, qtconsole, qscintilla, numpy, cycler, pyparsing, pytz, matplotlib, pyflakes, mu-editor
  Running setup.py install for pgzero ... done
  Running setup.py install for tornado ... done
  Running setup.py install for simplegeneric ... done
Successfully installed PyQtChart-5.10 appnope-0.1.0 cycler-0.10.0 decorator-4.2.1 ipykernel-4.8.2 ipython-6.2.1 ipython-genutils-0.2.0 jedi-0.11.1 jupyter-client-5.2.2 jupyter-core-4.4.0 matplotlib-2.1.2 mu-editor-1.0.0b15 numpy-1.14.1 parso-0.1.1 pexpect-4.4.0 pgzero-1.1 pickleshare-0.7.4 prompt-toolkit-1.0.15 ptyprocess-0.5.2 pycodestyle-2.3.1 pyflakes-1.6.0 pygame-1.9.3 pygments-2.2.0 pyparsing-2.2.0 pyqt5-5.10 pyserial-3.4 python-dateutil-2.6.1 pytz-2018.3 pyzmq-17.0.0 qscintilla-2.10.2 qtconsole-4.3.1 simplegeneric-0.8.1 sip-4.19.7 six-1.11.0 tornado-4.5.3 traitlets-4.3.2 wcwidth-0.1.7
(mu_beta) eddies-computer:mu_beta barry$ python3 -m mu
Logging to /Users/barry/Library/Logs/mu/mu.log
```

I took the code from the  [pygame zero introduction](https://pygame-zero.readthedocs.io/en/stable/introduction.html):
![image](https://user-images.githubusercontent.com/8608260/36505750-5df6d9b6-174c-11e8-90bd-c09fc38f6584.png)

When I press play I get the following error:
```
Traceback (most recent call last):
  File "/Users/barry/venvs/mu_beta/bin/pgzrun", line 11, in <module>
    load_entry_point('pgzero==1.1', 'console_scripts', 'pgzrun')()
  File "/Users/barry/venvs/mu_beta/lib/python3.6/site-packages/pgzero/runner.py", line 62, in main
    _substitute_full_framework_python()
  File "/Users/barry/venvs/mu_beta/lib/python3.6/site-packages/pgzero/runner.py", line 55, in _substitute_full_framework_python
    os.execv(framework_python, ['python', '-m', 'pgzero'] + sys.argv[1:])
FileNotFoundError: [Errno 2] No such file or directory


---------- FINISHED ----------
exit code: 1 status: 0
```

Information from mu.log:
```
2018-02-21 21:03:27,122 - mu.logic:435(restore_session) INFO: Loaded files.
2018-02-21 21:03:27,139 - mu.logic:712(change_mode) INFO: Workspace directory: /Users/barry/mu_code
2018-02-21 21:03:37,279 - mu.logic:466(new) INFO: Added a new tab.
2018-02-21 21:04:21,907 - mu.logic:732(autosave) INFO: Autosave has detected changes.
2018-02-21 21:04:26,908 - mu.logic:732(autosave) INFO: Autosave has detected changes.
2018-02-21 21:04:31,908 - mu.logic:732(autosave) INFO: Autosave has detected changes.
2018-02-21 21:04:39,270 - mu.logic:732(autosave) INFO: Autosave has detected changes.
2018-02-21 21:04:41,907 - mu.logic:732(autosave) INFO: Autosave has detected changes.
2018-02-21 21:04:45,653 - mu.interface.main:239(get_save_path) DEBUG: Getting save path: /Users/barry/mu_code/test_pygame
2018-02-21 21:04:45,668 - mu.logic:533(save) INFO: Saving script to: /Users/barry/mu_code/test_pygame.py
2018-02-21 21:04:45,668 - mu.logic:534(save) DEBUG: 
WIDTH = 300
HEIGHT = 300

def draw():
    screen.fill((128, 0, 0))

2018-02-21 21:04:57,396 - mu.modes.pygamezero:118(run_game) DEBUG: 
WIDTH = 300
HEIGHT = 300

def draw():
    screen.fill((128, 0, 0))

2018-02-21 21:04:57,401 - mu.interface.panes:602(start_process) INFO: Running script: /Users/barry/mu_code/test_pygame.py
2018-02-21 21:04:57,402 - mu.interface.panes:607(start_process) INFO: Command args: []
2018-02-21 21:04:57,402 - mu.interface.panes:613(start_process) INFO: Working directory: /Users/barry/mu_code
2018-02-21 21:04:57,402 - mu.interface.panes:618(start_process) INFO: Python path: ['', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/Users/barry/venvs/mu_beta/lib/python3.6/site-packages', '/Users/barry/venvs/mu_beta/lib/python3.6/site-packages/IPython/extensions']
2018-02-21 21:05:36,687 - mu.logic:618(show_help) INFO: Showing help.
2018-02-21 21:23:05,268 - mu.modes.pygamezero:129(stop_game) DEBUG: Stopping script.
2018-02-21 21:23:06,955 - mu.modes.pygamezero:118(run_game) DEBUG: 
WIDTH = 300
HEIGHT = 300

def draw():
    screen.fill((128, 0, 0))

2018-02-21 21:23:06,968 - mu.interface.panes:602(start_process) INFO: Running script: /Users/barry/mu_code/test_pygame.py
2018-02-21 21:23:06,968 - mu.interface.panes:607(start_process) INFO: Command args: []
2018-02-21 21:23:06,968 - mu.interface.panes:613(start_process) INFO: Working directory: /Users/barry/mu_code
2018-02-21 21:23:06,968 - mu.interface.panes:618(start_process) INFO: Python path: ['', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/Users/barry/venvs/mu_beta/lib/python3.6/site-packages', '/Users/barry/venvs/mu_beta/lib/python3.6/site-packages/IPython/extensions']
```

These are the details of the system I am running on:
![image](https://user-images.githubusercontent.com/8608260/36506434-8b8a28f4-174e-11e8-86c4-be2b43691e4f.png)

**Comment by ukBaz** [comment] 2018-02-21 22:00
I was working off the tweet from earlier today. I have now gone and read the _Developer Setup_ instructions for mu and noticed the requirement for the `--system-site-packages` flag.

If I now install with:
```
eddies-computer:~ barry$ python3 -m venv --system-site-packages venvs/mu_beta2
eddies-computer:~ barry$ cd venvs/mu_beta2/
eddies-computer:mu_beta2 barry$ source bin/activate
(mu_beta2) eddies-computer:mu_beta2 barry$ pip3 install mu-editor
```
All is working fine for me.

**Comment by carlosperate** [comment] 2018-02-21 23:55
That's odd, you shouldn't need to use the `--system-site-packages` flag, as all the packages should have been installed inside the virtual environment. Usually that flag is necessary when some package are added via installer, like older versions of PyQt, or PyQt in Raspbian as it is installed via `apt-get`.

Could you run the virtualenv without the flag and see what this line throws? (Ideally with the test program in a `myfile.py`)
```
python -m pgzero myfile.py
```

**Comment by ukBaz** [comment] 2018-02-22 06:58
Run as requested in the virtualenv that was created without the flag

```
(mu_beta) eddies-computer:mu_code barry$ python -m pgzero myfile.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/barry/venvs/mu_beta/lib/python3.6/site-packages/pgzero/__main__.py", line 3, in <module>
    main()
  File "/Users/barry/venvs/mu_beta/lib/python3.6/site-packages/pgzero/runner.py", line 62, in main
    _substitute_full_framework_python()
  File "/Users/barry/venvs/mu_beta/lib/python3.6/site-packages/pgzero/runner.py", line 55, in _substitute_full_framework_python
    os.execv(framework_python, ['python', '-m', 'pgzero'] + sys.argv[1:])
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by ntoll** [comment] 2018-05-03 15:59
I cannot reproduce... so closing. :-/

Please feel free to re-open if you try the steps I describe above, but the problem persists.

Thanks!

**Closed by ntoll** 2018-05-03 15:59 UTC
