### ISSUE TITLE
Files Panel: Clicking on the widget list resets the panel height

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#460] opened 2018-05-02 09:43 UTC
Tested on macOS High Sierra with the latest master at the time of writing:

![files panel size gif](https://user-images.githubusercontent.com/4189262/39516660-834acf30-4df5-11e8-8d16-3082587830e3.gif)

**Comment by ntoll** [comment] 2018-05-02 15:53
I too cannot reproduce on Linux. Could this be a Qt5 bug in OSX..?

**Comment by ZanderBrown** [comment] 2018-05-02 16:26
@ntoll that would seem likely, @carlosperate are all panels affected?

**Comment by carlosperate** [comment] 2018-05-02 17:12
Yeah, I could be a PyQt bug, I'm using PyQt5==5.10.1, I assume we are all on the same version?
There are no other panes with similar configuration, so it doesn't happen with the others.

**Comment by ntoll** [comment] 2018-05-03 15:46
Folks, the problem with the dangling file system panels is fixed in ff7bb826a8304a721f317ec9785afc4d65232d26. I'll leave this open until we can be certain this is a Qt bug.

**Comment by ntoll** [comment] 2018-06-04 20:43
Since I've not heard anything to suggest otherwise, I guess this IS a Qt bug.

**Closed by ntoll** 2018-06-04 20:43 UTC

**Comment by carlosperate** [comment] 2018-07-06 08:20
Just a note to say that this is still present on PyQt5 5.11.
