### ISSUE TITLE
I can't access it

### ISSUE THREAD

**Issue by fusee203** [mu-editor/mu#1720] opened 2021-07-24 13:45 UTC
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.5
Locale: en_US
Platform: Windows 10 10.0.17763 AMD64

```
m_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Windows 10\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Windows 10\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Windows 10\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Windows 10\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Windows 10\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Windows 10\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Windows 10\AppData\Local\python\mu\mu_venv-38-20210724-202752\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\WINDOW~1\AppData\Local\Temp\tmp3vqs6ql3\backcall-0.2.0-py2.py3-none-any.whl'

```

**Comment by carlosperate** [comment] 2021-08-02 17:52
Thanks for the report @fusee203!
I'll close this one as a duplicate of https://github.com/mu-editor/mu/issues/1723 and we can continue the debugging over there 👍

**Closed by carlosperate** 2021-08-02 17:52 UTC
