### ISSUE TITLE
Setting microbit_runtime_hex in settings.json has no effect

### ISSUE THREAD

**Issue by WayneKeenan** [mu-editor/mu#435] opened 2018-04-11 16:00 UTC
I'm trying to get `mu` to use a custom firmware by setting `microbit_runtime_hex ` in my`~/Library/Application\ Support/mu/settings.json` file, but it has no effect, examples:

```
{
  "theme": "day",
  "workspace": "/Users/wayne/mu_code",
  "paths": [],
  "microbit_runtime_hex": "microbit-blue-pairing-not-required.hex"
}
```

and

```
{
  "theme": "day",
  "workspace": "/Users/wayne/mu_code",
  "paths": [],
  "microbit_runtime_hex": "/Users/wayne/Library/Application Support/mu/microbit-blue-pairing-not-required.hex"
}
```

**Comment by ntoll** [comment] 2018-04-11 16:01
This is duplicate of #434

**Comment by ntoll** [comment] 2018-04-11 16:03
Sorry... my mistake. This needs investigating.

**Comment by ntoll** [comment] 2018-04-13 19:11
This has been fixed by  bf8bb75 which just landed in master. It'll be in beta.16

**Closed by ntoll** 2018-04-13 19:11 UTC
