### ISSUE TITLE
Ability to remove essential packages (pip, setuptools, wheel)

### ISSUE THREAD

**Issue by dybber** [mu-editor/mu#1224] opened 2021-01-07 10:32 UTC
Hi all,

I just played around with the new master branch, which contains the new virtualenv based backend for managing installed packages. However, I found a way to remove pip, which makes Mu crash when you try to launch it again.

Here are the steps:
 - Install some third party package (e.g. packagedummy)
 - Close mu
 - Open mu again
 - Open the Third Party Packages, now pip, setuptools and wheel are added to the list:

![Screenshot 2021-01-07 at 11 30 41](https://user-images.githubusercontent.com/55204/103882258-d36b0c00-50db-11eb-909a-e8028c499b6a.png)

 - Remove pip from the list and click Ok:

![Screenshot 2021-01-07 at 11 31 35](https://user-images.githubusercontent.com/55204/103882359-f695bb80-50db-11eb-9bd3-71b91846257e.png)

 - Try opening the admin dialog again

Mu crashes with the following error:

```
Traceback (most recent call last):
  File "/Users/dpr964/Development/micropython/mu/mu/virtual_environment.py", line 261, in installed
    next(iterlines)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dpr964/Development/micropython/mu/mu/logic.py", line 1394, in show_admin
    baseline_packages, user_packages = venv.installed_packages()
  File "/Users/dpr964/Development/micropython/mu/mu/virtual_environment.py", line 519, in installed_packages
    for package, version in self.pip.installed():
  File "/Users/dpr964/Development/micropython/mu/mu/virtual_environment.py", line 267, in installed
    raise VirtualEnvironmentError("Unable to parse installed packages")
mu.virtual_environment.VirtualEnvironmentError: Unable to parse installed packages
```

**Comment by tjguk** [comment] 2021-01-07 10:35
Thanks, @dybber  -- that's just the kind of thing I knew we'd have to addressing once the branch had landed. One probably simple workaround here is to include pip, setuptools etc. in our list of baseline packages so they will be excluded from the user's view.

**Comment by dybber** [comment] 2021-01-07 10:40
If you install a package that depends on PyQt5, you can also remove PyQt5. However, I can still launch it afterwards. But maybe that's because I have PyQt5 in the development environment? I'm not sure exactly what happens, but it is somehow removed, but still there:

![Screenshot 2021-01-07 at 11 35 34](https://user-images.githubusercontent.com/55204/103882822-a703bf80-50dc-11eb-996a-e174c856801e.png)

Perhaps the real issue here is that it installed that dependency instead of just using PyQt5 version already available with mu?

(This was after installing the package `AgentsPy` which were developing at the moment for agent-based simulation like Netlogo - possibly to be renamed to `netturtle` to make it closer to `turtle`)

**Comment by dybber** [comment] 2021-01-07 11:14
I think all packages installed as dependencies shouldn't be shown in the dialog, but should be automatically removed when no longer required by any packages. It should only list packages the user has installed, or perhaps a greyed out list of all packages installed, so the user cannot change it

**Comment by tjguk** [comment] 2021-02-03 17:14
I was starting to look at the first element of this -- excluding pip, setuptools etc. And I couldn't reproduce it. In fact, the baseline packages held in venv.json include pip, setuptools & wheel. So there's no need to exclude them specifically.

I agree that it would be good to track "topline" packages separately from their dependencies. I'll try to put a PR together

**Comment by carlosperate** [comment] 2021-08-04 19:32
I believe Tim has already resolved this by storing the "base" dependencing in the venv.json file and not displaying them to the user, so they cannot be removed:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/4189262/128243408-3db47a54-d890-4f08-93ef-912e04870543.png">

I'll close this as resolved, but feel free to reopen if this is still an issue 👍 

Thanks everyone!

**Closed by carlosperate** 2021-08-04 19:32 UTC
Labels: bug
