### ISSUE TITLE
Experiencing an NSIS error after downloading latest 64-bit Windows version

### ISSUE THREAD

**Issue by CedarGroveStudios** [mu-editor/mu#700] opened 2018-11-08 07:22 UTC
… from the website. The download reported typical progress for a 94MB file, but the file size stored on the system was 47MB. When executed (as admin) it threw an "NSIS Error: Installer integrity check has failed. Common causes include incomplete download and damaged media. Contact the installer's author to obtain a new copy."

I tried it multiple times. The only difference was the size of the resultant file. 

In the past, previous versions downloaded successfully. Is there an issue with the Windows installation package or am I doing something wrong?

Thanks!

Windows 10 64-bit

![nsis error window](https://user-images.githubusercontent.com/29906257/48183559-f0310c80-e2e3-11e8-900e-e10fc8980417.PNG)

**Comment by carlosperate** [comment] 2018-11-08 08:45
The problem is likely to be an incomplete download, as the excutables from the website have been tested to work.

In this case the files are provided by GitHub, and there isn't any reported issues in that area.

Sounds like this might be an issue with your internet connexion, provider, or network. Could you try downloading again, from a different computer, or a different network?

**Comment by CedarGroveStudios** [comment] 2018-11-08 17:33
Thank you for your response. 
Will do. I'll touch base with my provider, too.
For a data point, I've recently downloaded install executable packages from a number of other sites, including git, with no issues. In one case, the wrapper file was nearly 2GB.

**Comment by tjguk** [comment] 2018-11-09 18:47
I'm afraid I'm going to close this "can't reproduce".

I've just successfully downloaded and installed from https://github.com/mu-editor/mu/releases/download/1.0.1/mu-editor_1.0.1_win64.exe which, as @carlosperate points out is hosted by Github so outside our control (and generally fairly reliable). And we've had no other reports of this kind.

I can only suggest that perhaps some kind of webfilter/firewall or security scanning at your end is producing this effect.

**Closed by tjguk** 2018-11-09 18:47 UTC
