### ISSUE TITLE
Windows 10 Intermittent Hangs in 1.0.1

### ISSUE THREAD

**Issue by TheKitty** [mu-editor/mu#665] opened 2018-10-03 15:20 UTC
If you are reporting a bug, we would like to know:

* What you were trying to do, 
Use Mu 1.0.1 on Windows 10 latest build

* What steps you took to make this happen, 
normal get file, edit file, save file

* What you expected to happen, 
normal file handling

* What actually happened, 
Window becomes unresponsive, task pythonw reported by Win10 as taking 21% of CPU and task is "nonresponsive"

* Why this difference is problematic (it may not be a bug!),
Window hangs - can't do anything
![image](https://user-images.githubusercontent.com/1911920/46419780-9ba2dc00-c6fc-11e8-82d6-da9187675715.png)

* Technical details like the version of Mu you're using, your OS version and
  other aspects of the context in which Mu was running. 
Given above

Please remember to attach a **copy of the full log files for Mu**. You can get
the logs by clicking on the cog icon in the bottom right of the editor window.
Click on the logs and use CTRL-A to select all, then CTRL-C to copy and CTRL-V
to paste the contents into the issue.

```
2018-10-03 11:17:46,853 - root:112(run) INFO: 

-----------------

Starting Mu 1.0.1
2018-10-03 11:17:46,856 - root:113(run) INFO: uname_result(system='Windows', node='Dad-2012', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
2018-10-03 11:17:46,856 - root:114(run) INFO: Python path: ['C:\\Program Files\\Mu\\pkgs', 'C:\\Program Files\\Mu\\Python\\python36.zip', 'C:\\Program Files\\Mu\\Python', 'C:\\Program Files\\Mu\\pkgs', 'C:\\Program Files\\Mu\\pkgs\\IPython\\extensions']
2018-10-03 11:17:46,856 - root:115(run) INFO: Language code: en_US
2018-10-03 11:17:47,199 - mu.logic:540(__init__) INFO: Setting up editor.
2018-10-03 11:17:47,200 - mu.logic:558(__init__) INFO: Settings path: C:\Users\Mike\AppData\Local\python\mu\settings.json
2018-10-03 11:17:47,200 - mu.logic:559(__init__) INFO: Session path: C:\Users\Mike\AppData\Local\python\mu\session.json
2018-10-03 11:17:47,200 - mu.logic:560(__init__) INFO: Log directory: C:\Users\Mike\AppData\Local\python\mu\Logs
2018-10-03 11:17:47,200 - mu.logic:561(__init__) INFO: Data directory: C:\Users\Mike\AppData\Local\python\mu
2018-10-03 11:17:47,230 - mu.logic:574(setup) INFO: Available modes: python, adafruit, microbit, debugger, pygamezero
2018-10-03 11:17:47,831 - mu.logic:1112(change_mode) INFO: Workspace directory: C:\Users\Mike\mu_code
2018-10-03 11:17:47,835 - mu.logic:623(restore_session) INFO: Restoring session from: C:\Users\Mike\AppData\Local\python\mu\session.json
2018-10-03 11:17:47,835 - mu.logic:624(restore_session) DEBUG: {'theme': 'day', 'mode': 'adafruit', 'paths': ['Z:\\Adafruit\\- Work Products\\Guide edits\\CRICKIT\\Intro Crickit\\microbit\\microbit-neo.py', 'Z:\\Adafruit\\- Work Products\\Guide edits\\Make it ___\\Pulse\\pulse.py', 'Z:\\Adafruit\\- Work Products\\Guide edits\\Make it ___\\Pulse\\df2t.py', 'Z:\\Adafruit\\- Work Products\\Guide edits\\Make it ___\\Pulse\\dft.py', 'Z:\\Adafruit\\- Work Products\\Guide edits\\Make it ___\\hot-cold\\code-cpx-final.py', 'I:\\code.py'], 'envars': [], 'minify': False, 'microbit_runtime': ''}
2018-10-03 11:17:47,835 - mu.logic:708(_load) INFO: Loading script from: Z:\Adafruit\- Work Products\Guide edits\Make it ___\Pulse\pulse.py
2018-10-03 11:17:47,843 - mu.logic:271(read_and_decode) DEBUG: Trying to decode with utf-8
2018-10-03 11:17:47,844 - mu.logic:274(read_and_decode) INFO: Decoded with utf-8
2018-10-03 11:17:47,845 - mu.logic:287(read_and_decode) DEBUG: Detected newline '\n'
2018-10-03 11:17:47,845 - mu.logic:782(_load) DEBUG: # Adafruit Circuit Playground Express Pulse Monitor
#
# This code uses the light sensor built in to Circuit Playground Express
# to detect the pulse of a finger.
# Save this code as code.py on a Circuit Playground Express board running
# CircuitPython (see https://github.com/adafruit/circuitpython).  You will
# also need to load neopixel.mpy onto the board's /lib folder (from
# https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/releases).
#
# When the first three NeoPixels light up white you're ready to read -
# the light sensor (look for the eye graphic on the board, it's right
# below the three lit NeoPixels) and look at the serial terminal from the board
# at 115200 baud to see pulse rate printed.  This works best
# holding your finger perpendicular to the sensor, like:
#       ||
#       || <- Finger
#       ||
#    ________  <- Circuit Playground
#
# Author: Mike Barela for Adafruit Industries, 9/2018
# License: MIT License (https://en.wikipedia.org/wiki/MIT_License)
import time
import array
 
import board
import analogio
import neopixel
 
# Configuration:
SPINNER_ARMS           = 3       # Number of arms on the fidget spinner.
                                 # This is used to calculate the true
                                 # revolutions per second of the spinner
                                 # as one full revolution of the spinner
                                 # will actually see this number of cycles
                                 # pass by the light sensor.  Set this to
                                 # the value 1 to ignore this calculation
                                 # and just see the raw cycles / second.
 
SAMPLE_DEPTH           = 256     # How many samples to take when measuring
                                 # the spinner speed.  The larger this value
                                 # the more memory that will be consumed but
                                 # the slower a spinner speed that can be
                                 # detected (larger sample depths mean longer
                                 # period waves can be detected).  You're
                                 # limited by the amount of memory on the
                                 # board for this value.
 
TARGET_SAMPLE_RATE_HZ  = 150     # Target sample rate for sampling the light
                                 # sensor.  This in combination with the sample
                                 # depth above controls how slow and fast of
                                 # a signal you can detect.  Note that the
                                 # sample rate can only go so high before it's
                                 # too fast for the Python interpreted code
                                 # to run.  If that happens the board will
                                 # light up LEDs red to indicate the 'underflow'
                                 # condition (drop the sample rate down to
                                 # a lower value and try again).
                                 # A value of 150 times a second means you can
                                 # measure a spinner going up to 25 revolutions
                                 # per second.
 
THRESHOLD              =  100    # How big the magnitude of a cyclic
                                 # signal has to be before the measurement
                                 # logic kicks in.  This is a value from
                                 # 0 to 65535 and might need to be adjusted
                                 # up or down if the detection is too
                                 # sensitive or not sensitive enough.
                                 # Raising this value will make the detection
                                 # less sensitive and require a very large
                                 # difference in amplitude (i.e. a very close
                                 # or highly reflective spinner), and lowering
                                 # the value will make the detection more
                                 # sensitive and potentially pick up random
                                 # noise from light in the room.
 
 
# Configure NeoPixels and turn them all off at the start.
pixels = neopixel.NeoPixel(board.NEOPIXEL, 10)
pixels.fill((0,0,0))
pixels.write()

# Configure analog input for light sensor
light = analogio.AnalogIn(board.LIGHT)

# Take an initial set of readings and measure how long it takes.
# This is used to calculate a delay between readings to hit the desired
# target sample rate.  Use the array module to preallocate an array of 16-bit
# unsigned samples with lower memory overhead vs. a simple python list.
readings = array.array('H', [0]*SAMPLE_DEPTH)
start = time.monotonic()
for i in range(SAMPLE_DEPTH):
    readings[i] = light.value
stop = time.monotonic()
print((stop-start)*1000.0)

# Calculate how long it took to take all the readings above, then figure out
# the difference from the target period to actual period.  This difference is
# the amount of time to delay between sample readings to hit the desired target
# sample rate.
target_period = 1.0/TARGET_SAMPLE_RATE_HZ
actual_period = (stop-start)/SAMPLE_DEPTH
delay = 0
# Check that we can sample fast enough to hit the target rate.
if actual_period > target_period:
    # Uh oh can't sample fast enough--print a warning and light up pixels red.
    print('Could not hit desired target sample rate!')
    pixels.fill((0,0,255))
    pixels.write()
else:
    # No problem hitting target sample rate so calculate the delay between
    # samples to hit that desired rate.  Then turn on the first two pixels
    # to red full brightness.
    delay = target_period - actual_period
    pixels[0] = (255, 0, 0)
    pixels[1] = (255, 0, 0)
#    pixels[2] = (255, 0, 0)
    pixels.write()

# Main loop:
while True:
    # Pause for a second between readings.
    time.sleep(1.0)
    # Grab a set of samples and measure the time it took to do so.
    start = time.monotonic()
    for i in range(SAMPLE_DEPTH):
        readings[i] = light.value
        time.sleep(delay)  # Sleep for the delay calculated to hit target rate.
    stop = time.monotonic()
    elapsed = stop - start
    # Find the min and max readings from the samples.
    minval = readings[0]
    maxval = readings[0]
    for r in readings:
        minval = min(minval, r)
        maxval = max(maxval, r)
    # Calculate magnitude or size of the signal.  If the magnitude doesn't
    # pass the threshold then start over with a new sample (run the loop again).
    magnitude = maxval - minval
    if magnitude < THRESHOLD:
        print("No variance > 100")
        continue
    # Calculate the midpoint of the signal, then count how many times the
    # signal crosses the midpoint.
    midpoint = minval + magnitude/2.0
    crossings = 0
    for i in range(1, SAMPLE_DEPTH):
        p0 = readings[i-1]
        p1 = readings[i]
        # Check if a pair of points crossed the midpoint either by hitting it
        # exactly or hitting it going up or down.
        if p1 == midpoint or p0 < midpoint < p1 or p0 > midpoint > p1:
           crossings += 1
    # Finally use the number of crosssings and the amount of time in the sample
    # window to calculate how many times the pulse was detected
    # sensor.  Use that period to calculate frequency (rotations per second)
    # and RPM (rotations per minute).
    period = elapsed / (crossings / 2.0 / SPINNER_ARMS)
    frequency = 1.0/period
    bpm = frequency * 60.0
    print('Frequency: {0:0.5} (hz)\t\tRPM: {1:0.5}\t\tPeriod: {2:0.5} (seconds)'.format(frequency, bpm, period))
2018-10-03 11:17:48,425 - mu.logic:708(_load) INFO: Loading script from: Z:\Adafruit\- Work Products\Guide edits\Make it ___\Pulse\dft.py
2018-10-03 11:17:48,430 - mu.logic:271(read_and_decode) DEBUG: Trying to decode with utf-8
2018-10-03 11:17:48,431 - mu.logic:274(read_and_decode) INFO: Decoded with utf-8
2018-10-03 11:17:48,431 - mu.logic:287(read_and_decode) DEBUG: Detected newline '\n'
2018-10-03 11:17:48,431 - mu.logic:782(_load) DEBUG: # Adafruit Circuit Playground Express Pulse Monitor
#
# This code uses the light sensor built in to Circuit Playground Express
# to detect the pulse of a finger.
# Save this code as code.py on a Circuit Playground Express board running
# CircuitPython (see https://github.com/adafruit/circuitpython).  You will
# also need to load neopixel.mpy onto the board's /lib folder (from
# https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/releases).
#
# When the first three NeoPixels light up white you're ready to read -
# the light sensor (look for the eye graphic on the board, it's right
# below the three lit NeoPixels) and look at the serial terminal from the board
# at 115200 baud to see pulse rate printed.  This works best
# holding your finger perpendicular to the sensor, like:
#       ||
#       || <- Finger
#       ||
#    ________  <- Circuit Playground
#
# Author: Mike Barela for Adafruit Industries, 9/2018
# License: MIT License (https://en.wikipedia.org/wiki/MIT_License)
import time
import array
import math
 
import board
import analogio
import neopixel
 
# Configuration:
SAMPLE_DEPTH          = 256     # How many samples to take when measuring
                                # the light value.  The larger this value
                                # the more memory that will be consumed but
                                # the slower a pulse that can be
                                # detected (larger sample depths mean longer
                                # period waves can be detected).  You're
                                # limited by the amount of memory on the
                                # board for this value.
 
TARGET_SAMPLE_RATE_HZ  = 20     # Assuming a high heart rate of 120 bpm,
                                # we can compute the minimum sampling rate using the
                                # Nyquist-Shannon sampling theorem as follows: The
                                # heartbeats per second = 120/60 =2 bps The minimum
                                # sampling frequency = 2×2 = 4 samples per second.
                                # In our implementation, the MCU reads the input
                                # signal at a rate of 20 samples per second, i.e.
                                # well above the minimum sampling rate computed above

THRESHOLD              =  100    # How big the magnitude of a cyclic
                                 # signal has to be before the measurement
                                 # logic kicks in.  This is a value from
                                 # 0 to 65535 and might need to be adjusted
                                 # up or down if the detection is too
                                 # sensitive or not sensitive enough.
                                 # Raising this value will make the detection
                                 # less sensitive and require a very large
                                 # difference in amplitude, and lowering
                                 # the value will make the detection more
                                 # sensitive and potentially pick up random
                                 # noise from light in the room.
                                 
# Discrete Fourier transform (Python) by Project Nayuki, 2017. Public domain.
# https://www.nayuki.io/page/how-to-implement-the-discrete-fourier-transform
# 
# (Alternate implementation using only real numbers.)
# Computes the discrete Fourier transform (DFT) of the given complex vector.
# 'inreal' and 'inimag' are each a sequence of n floating-point numbers.
# Returns a tuple of 2 lists of floats - outreal and outimag, each of length n.
# 
def compute_dft_real_pair(inreal):
    n = len(inreal)	
    inimag = [0] * n
    outreal = list()
#	outimag = []
    for k in range(n):  # For each output element
        sumreal = 0.0
        sumimag = 0.0
        for t in range(n):  # For each input element
            angle = 2 * math.pi * t * k / n
            sumreal += inreal[t] * math.cos(angle) +
                        inimag[t] * math.sin(angle)
            sumimag += -inreal[t] * math.sin(angle) +
                        inimag[t] * math.cos(angle)
        outreal.append(sqrt(sumreal*sumreal+sumimag*sumimag))
#		outimag.append(sumimag)
	return (outreal)
 
 
# Configure NeoPixels and turn them all off at the start.
pixels = neopixel.NeoPixel(board.NEOPIXEL, 10)
pixels.fill((0, 0, 0))
pixels.write()

# Configure analog input for light sensor
light = analogio.AnalogIn(board.LIGHT)

# Take an initial set of readings and measure how long it takes.
# This is used to calculate a delay between readings to hit the desired
# target sample rate.  Use the array module to preallocate an array of 16-bit
# unsigned samples with lower memory overhead vs. a simple python list.
readings = array.array('H', [0]*SAMPLE_DEPTH)
start = time.monotonic()
for i in range(SAMPLE_DEPTH):
    readings[i] = light.value
stop = time.monotonic()
print((stop-start)*1000.0)  # Getting about 50

# Calculate how long it took to take all the readings above, then figure out
# the difference from the target period to actual period.  This difference is
# the amount of time to delay between sample readings to hit the desired target
# sample rate.
target_period = 1.0/TARGET_SAMPLE_RATE_HZ
actual_period = (stop-start)/SAMPLE_DEPTH
delay = 0
# Check that we can sample fast enough to hit the target rate.
if actual_period > target_period:
    # Uh oh can't sample fast enough--print a warning and light up pixels red.
    print('Could not hit desired target sample rate!')
    pixels.fill((0, 0, 255))
    pixels.write()
else:
    # No problem hitting target sample rate so calculate the delay between
    # samples to hit that desired rate.  Then turn on the first two pixels
    # to red full brightness.
    delay = target_period - actual_period
    print('delay ')
    print(delay)
#    pixels[0] = (255, 0, 0)
    pixels[1] = (255, 255, 255)
#    pixels[2] = (255, 0, 0)
    pixels.write()

# Main loop:
while True:
    # Pause between readings.
    print("sleep between readings")
    time.sleep(2.0)
    # Grab a set of samples and measure the time it took to do so.
    start = time.monotonic()
    for i in range(SAMPLE_DEPTH):
        readings[i] = light.value
        time.sleep(delay)  # Sleep for the delay calculated to hit target rate.
    stop = time.monotonic()
    elapsed = stop - start
    # Find the min and max readings from the samples.
    minval = readings[0]
    maxval = readings[0]
    for r in readings:
        minval = min(minval, r)
        maxval = max(maxval, r)
    # Calculate magnitude or size of the signal.  If the magnitude doesn't
    # pass the threshold then start over with a new sample (run loop again).
    magnitude = maxval - minval
    print(magnitude)
    if magnitude < THRESHOLD:
        print("No variance > Threshold")
        continue
    # Calculate the midpoint of the signal, then count how many times the
    # signal crosses the midpoint.
    midpoint = minval + magnitude/2.0
    crossings = 0
    for i in range(1, SAMPLE_DEPTH):
        p0 = readings[i-1]
        p1 = readings[i]
        # Check if a pair of points crossed the midpoint either by hitting it
        # exactly or hitting it going up or down.
        if p1 == midpoint or p0 < midpoint < p1 or p0 > midpoint > p1:
            crossings += 1
        print((readings[i]-midpoint,))
        time.sleep(0.1)
    # Finally use the number of crosssings and the amount of time in the sample
    # window to calculate how many times the pulse was detected with
    # sensor.  Use that period to calculate frequency (beats per second)
    # and BPM (beats per minute).
    period = elapsed / (crossings / 2.0)
    frequency = 1.0/period
    bpm = frequency * 60.0
    print('Frequency: {0:0.5} (hz)\t\tBPM: {1:0.5}\t\tPeriod: {2:0.5} (seconds)'.format(frequency, bpm, period))
2018-10-03 11:17:48,447 - mu.logic:708(_load) INFO: Loading script from: I:\code.py
2018-10-03 11:17:48,447 - mu.logic:717(_load) INFO: The file I:\code.py does not exist.
2018-10-03 11:17:48,447 - mu.logic:708(_load) INFO: Loading script from: Z:\Adafruit\- Work Products\Guide edits\Make it ___\hot-cold\code-cpx-final.py
2018-10-03 11:17:48,452 - mu.logic:271(read_and_decode) DEBUG: Trying to decode with utf-8
2018-10-03 11:17:48,452 - mu.logic:274(read_and_decode) INFO: Decoded with utf-8
2018-10-03 11:17:48,452 - mu.logic:287(read_and_decode) DEBUG: Detected newline '\n'
2018-10-03 11:17:48,452 - mu.logic:782(_load) DEBUG: import time
import board
from analogio import AnalogIn
from adafruit_crickit import crickit
import neopixel

print("Peltier Module Demo")

pixels = neopixel.NeoPixel(board.NEOPIXEL, 10, auto_write=False)

def show_value(time_val):         # Show time on NeoPixels on CPX
    num_pixels = int(10-time_val)
    for i in range(num_pixels):
        pixels[i] = (10*(i+1), 0, 0)
    for i in range(num_pixels, 10):
        pixels[i] = (0, 0, 0)
    pixels.show()
    return

TMP36 = AnalogIn(board.A3)  # TMP36 connected to A3, power & ground
POT = AnalogIn(board.A7)    # potentiometer connected to A7, power & ground

peltier = crickit.dc_motor_2  # Drive the Peltier from Motor 2 Output

while True:                   # Loop forever

    voltage = TMP36.value * 3.3 / 65536.0
    tempC = (voltage - 0.5) * 100.0
    tempF = (tempC * 9.0 / 5.0) + 32.0

    cool_value = POT.value / 6553.6  # convert 0.0 to 10.0

    # timing can be zero or can be 1 second to 10 seconds
    # between 0 and 1 is too short a time for a Peltier module
    if cool_value < 0.2:
        cool_value = 0.0
    if cool_value >= 0.2 and cool_value < 1.0:
        cool_value = 1.0

    print((tempF, cool_value))  # Show in REPL
    show_value(cool_value)      # Show on NeoPixels

    # Peltier cannot be PWM - either off or on
    # Use potentiometer read to set seconds b
    if cool_value > 0:
        peltier.throttle = 0.0     # turn off
        time.sleep(cool_value)     # wait

    peltier.throttle = 1.0         # turn on
    time.sleep(10.0 - cool_value)  # wait
2018-10-03 11:17:48,468 - mu.logic:708(_load) INFO: Loading script from: Z:\Adafruit\- Work Products\Guide edits\CRICKIT\Intro Crickit\microbit\microbit-neo.py
2018-10-03 11:17:48,474 - mu.logic:271(read_and_decode) DEBUG: Trying to decode with utf-8
2018-10-03 11:17:48,474 - mu.logic:274(read_and_decode) INFO: Decoded with utf-8
2018-10-03 11:17:48,474 - mu.logic:287(read_and_decode) DEBUG: Detected newline '\n'
2018-10-03 11:17:48,474 - mu.logic:782(_load) DEBUG: # Drive NeoPixels on the NeoPixels Block on Crickit for micro:bit
#  
import time
import neopixel
import board
 
num_pixels = 30  # Number of pixels driven from Crickit NeoPixel terminal
 
# The following line sets up a NeoPixel strip on Crickit pn P16
pixels = neopixel.NeoPixel(board.A1, num_pixels, brightness=0.3,
                           auto_write=False)
 
def wheel(pos):
    # Input a value 0 to 255 to get a color value.
    # The colours are a transition r - g - b - back to r.
    if pos < 0 or pos > 255:
        return (0, 0, 0)
    if pos < 85:
        return (255 - pos * 3, pos * 3, 0)
    if pos < 170:
        pos -= 85
        return (0, 255 - pos * 3, pos * 3)
    pos -= 170
    return (pos * 3, 0, 255 - pos * 3)
 
def color_chase(color, wait):
    for i in range(num_pixels):
        pixels[i] = color
        time.sleep(wait)
        pixels.show()
    time.sleep(0.5)
 
def rainbow_cycle(wait):
    for j in range(255):
        for i in range(num_pixels):
            rc_index = (i * 256 // num_pixels) + j
            pixels[i] = wheel(rc_index & 255)
        pixels.show()
        time.sleep(wait)
 
RED = (255, 0, 0)
YELLOW = (255, 150, 0)
GREEN = (0, 255, 0)
CYAN = (0, 255, 255)
BLUE = (0, 0, 255)
PURPLE = (180, 0, 255)
 
while True:
    print("fill")
    pixels.fill(RED)
    pixels.show()
    # Increase or decrease to change the speed of the solid color change.
    time.sleep(1)
    pixels.fill(GREEN)
    pixels.show()
    time.sleep(1)
    pixels.fill(BLUE)
    pixels.show()
    time.sleep(1)
 
    print("chase")
    color_chase(RED, 0.1)  # Increase the number to slow down the color chase
    color_chase(YELLOW, 0.1)
    color_chase(GREEN, 0.1)
    color_chase(CYAN, 0.1)
    color_chase(BLUE, 0.1)
    color_chase(PURPLE, 0.1)
 
    print("rainbow")
    rainbow_cycle(0)  # Increase the number to slow down the rainbow
2018-10-03 11:17:48,493 - mu.logic:708(_load) INFO: Loading script from: Z:\Adafruit\- Work Products\Guide edits\Make it ___\Pulse\df2t.py
2018-10-03 11:17:48,500 - mu.logic:271(read_and_decode) DEBUG: Trying to decode with utf-8
2018-10-03 11:17:48,500 - mu.logic:274(read_and_decode) INFO: Decoded with utf-8
2018-10-03 11:17:48,501 - mu.logic:287(read_and_decode) DEBUG: Detected newline '\n'
2018-10-03 11:17:48,501 - mu.logic:782(_load) DEBUG: # Adafruit Circuit Playground Express Pulse Monitor
#
# This code uses the light sensor built in to Circuit Playground Express
# to detect the pulse of a finger.
# Save this code as code.py on a Circuit Playground Express board running
# CircuitPython (see https://github.com/adafruit/circuitpython).  You will
# also need to load neopixel.mpy onto the board's /lib folder (from
# https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/releases).
#
# When the first three NeoPixels light up white you're ready to read -
# the light sensor (look for the eye graphic on the board, it's right
# below the three lit NeoPixels) and look at the serial terminal from the board
# at 115200 baud to see pulse rate printed.  This works best
# holding your finger perpendicular to the sensor, like:
#       ||
#       || <- Finger
#       ||
#    ________  <- Circuit Playground
#
# Author: Mike Barela for Adafruit Industries, 9/2018
# License: MIT License (https://en.wikipedia.org/wiki/MIT_License)
import time
import array
import math
 
import board
import analogio
import neopixel
 
# Configuration:
SAMPLE_DEPTH          = 256     # How many samples to take when measuring
                                # the light value.  The larger this value
                                # the more memory that will be consumed but
                                # the slower a pulse that can be
                                # detected (larger sample depths mean longer
                                # period waves can be detected).  You're
                                # limited by the amount of memory on the
                                # board for this value.
 
TARGET_SAMPLE_RATE_HZ  = 20     # Assuming a high heart rate of 120 bpm,
                                # we can compute the minimum sampling rate using the
                                # Nyquist-Shannon sampling theorem as follows: The
                                # heartbeats per second = 120/60 =2 bps The minimum
                                # sampling frequency = 2×2 = 4 samples per second.
                                # In our implementation, the MCU reads the input
                                # signal at a rate of 20 samples per second, i.e.
                                # well above the minimum sampling rate computed above

THRESHOLD              =  100    # How big the magnitude of a cyclic
                                 # signal has to be before the measurement
                                 # logic kicks in.  This is a value from
                                 # 0 to 65535 and might need to be adjusted
                                 # up or down if the detection is too
                                 # sensitive or not sensitive enough.
                                 # Raising this value will make the detection
                                 # less sensitive and require a very large
                                 # difference in amplitude, and lowering
                                 # the value will make the detection more
                                 # sensitive and potentially pick up random
                                 # noise from light in the room.
                                 
# Discrete Fourier transform (Python) by Project Nayuki, 2017. Public domain.
# https://www.nayuki.io/page/how-to-implement-the-discrete-fourier-transform
# 
# (Alternate implementation using only real numbers.)
# Computes the discrete Fourier transform (DFT) of the given complex vector.
# 'inreal' and 'inimag' are each a sequence of n floating-point numbers.
# Returns a tuple of 2 lists of floats - outreal and outimag, each of length n.
# 
def compute_dft_real_pair(inreal):
    n = len(inreal)	
    inimag = [0] * n
    outreal = []
    # outimag = []
    for k in range(n):  # For each output element
        sumreal = 0.0
        sumimag = 0.0
        for t in range(n):  # For each input element
            angle = 2 * math.pi * t * k / n
            sumreal += inreal[t] * math.cos(angle) + inimag[t] * math.sin(angle)
            sumimag += -inreal[t] * math.sin(angle) + inimag[t] * math.cos(angle)
        abs = math.sqrt(sumreal*sumreal+sumimag*sumimag)
        outreal.append(abs)
        # outimag.append(sumimag)
    print("done with dfft")
    return outreal

# Configure NeoPixels and turn them all off at the start.
pixels = neopixel.NeoPixel(board.NEOPIXEL, 10)
pixels.fill((0, 0, 0))
pixels.write()

# Configure analog input for light sensor
light = analogio.AnalogIn(board.LIGHT)

# Take an initial set of readings and measure how long it takes.
# This is used to calculate a delay between readings to hit the desired
# target sample rate.  Use the array module to preallocate an array of 16-bit
# unsigned samples with lower memory overhead vs. a simple python list.
readings = array.array('H', [0]*SAMPLE_DEPTH)
start = time.monotonic()
for i in range(SAMPLE_DEPTH):
    readings[i] = light.value
stop = time.monotonic()
print((stop-start)*1000.0)  # Getting about 50

# Calculate how long it took to take all the readings above, then figure out
# the difference from the target period to actual period.  This difference is
# the amount of time to delay between sample readings to hit the desired target
# sample rate.
target_period = 1.0/TARGET_SAMPLE_RATE_HZ
actual_period = (stop-start)/SAMPLE_DEPTH
delay = 0
# Check that we can sample fast enough to hit the target rate.
if actual_period > target_period:
    # Uh oh can't sample fast enough--print a warning and light up pixels red.
    print('Could not hit desired target sample rate!')
    pixels.fill((0, 0, 255))
    pixels.write()
else:
    # No problem hitting target sample rate so calculate the delay between
    # samples to hit that desired rate.  Then turn on the first two pixels
    # to red full brightness.
    delay = target_period - actual_period
    print('delay ')
    print(delay)
#    pixels[0] = (255, 0, 0)
    pixels[1] = (255, 255, 255)
#    pixels[2] = (255, 0, 0)
    pixels.write()

# Main loop:
while True:
    # Pause between readings.
    print("sleep between readings")
    time.sleep(1.0)
    # Grab a set of samples and measure the time it took to do so.
    start = time.monotonic()
    for i in range(SAMPLE_DEPTH):
        readings[i] = light.value
        time.sleep(delay)  # Sleep for the delay calculated to hit target rate.
    stop = time.monotonic()
    elapsed = stop - start
    # Find the min and max readings from the samples.
    minval = readings[0]
    maxval = readings[0]
    for r in readings:
        minval = min(minval, r)
        maxval = max(maxval, r)
    # Calculate magnitude or size of the signal.  If the magnitude doesn't
    # pass the threshold then start over with a new sample (run loop again).
    magnitude = maxval - minval
    print(magnitude)
    if magnitude < THRESHOLD:
        print("No variance > Threshold")
        continue
    fft = []
    fft = compute_dft_real_pair(readings)
    print(len(fft))
    for j in range(SAMPLE_DEPTH/2+1):
        print((fft[j],))
    # Calculate the midpoint of the signal, then count how many times the
    # signal crosses the midpoint.
    midpoint = minval + magnitude/2.0
    crossings = 0
    for i in range(1, SAMPLE_DEPTH):
        p0 = readings[i-1]
        p1 = readings[i]
        # Check if a pair of points crossed the midpoint either by hitting it
        # exactly or hitting it going up or down.
        if p1 == midpoint or p0 < midpoint < p1 or p0 > midpoint > p1:
            crossings += 1
#        print((readings[i]-midpoint,))
        time.sleep(0.1)
    # Finally use the number of crosssings and the amount of time in the sample
    # window to calculate how many times the pulse was detected with
    # sensor.  Use that period to calculate frequency (beats per second)
    # and BPM (beats per minute).
    period = elapsed / (crossings / 2.0)
    frequency = 1.0/period
    bpm = frequency * 60.0
    print('Frequency: {0:0.5} (hz)\t\tBPM: {1:0.5}\t\tPeriod: {2:0.5} (seconds)'.format(frequency, bpm, period))
2018-10-03 11:17:48,523 - mu.logic:645(restore_session) INFO: Loaded files.
2018-10-03 11:17:48,523 - mu.logic:649(restore_session) INFO: User defined environment variables: []
2018-10-03 11:17:48,523 - mu.logic:653(restore_session) INFO: Minify scripts on micro:bit? False
2018-10-03 11:17:48,583 - mu.interface.main:711(show_message) DEBUG: Could not find an attached Adafruit CircuitPython device.
2018-10-03 11:17:48,583 - mu.interface.main:712(show_message) DEBUG: Python files for Adafruit CircuitPython devices are stored on the device. Therefore, to edit these files you need to have the device plugged in. Until you plug in a device, Mu will use the directory found here:

 C:\Users\Mike\mu_code

...to store your code.
2018-10-03 11:17:50,363 - mu.logic:1112(change_mode) INFO: Workspace directory: C:\Users\Mike\mu_code
2018-10-03 11:17:51,656 - mu.logic:1039(show_admin) INFO: Showing logs from 
```

Thank you for contributing to Mu! :-)

**Comment by TheKitty** [comment] 2018-10-03 15:37
On a hunch I unplugged my Circuit Playground Express, Mu hang corrected itself and it opened the load file dialog. There must be something in Windows USB that is causing pythonw to hang and not open file dialog boxes

**Comment by tjguk** [comment] 2018-10-03 19:41
Well this is going to be fun to debug! It would be interesting to know whether anyone else has experienced this with CircuitPlayground. Have you asked on CP forums? (I assume there are some).

Can you tell me whether it starts to respond if you leave it for long enough? I don't know how long you waited, but will it come back if you wait 1 minute? 5  minutes? 15?

The fact that it's consuming CPU is interesting because the natural hypothesis is that it's trying to talk to the filesystem on the CP device and waiting for some kind of ack. But by definition that's IO-bound and I wouldn't expect to see if chewing CPU

**Comment by tjguk** [comment] 2018-10-03 19:41
@ntoll Do you have a Circuit Playground? If you bring it tomorrow I can try against my Win10 box to see if we can reproduce

**Comment by carlosperate** [comment] 2018-10-03 20:31
Long shot, but does problem still happen if you turn off malwarebytes? Not that you should, but just trying to eliminate that as a possible cause.

**Comment by dhalbert** [comment] 2018-10-03 20:35
We also have issues with Kaspersky, AIDA64, and Hard Disk Sentinel.

**Comment by carlosperate** [comment] 2018-10-03 20:38
> We also have issues with Kaspersky, AIDA64, and Hard Disk Sentinel.

Do you mean you've seen this issue in Mu when run alongside those applications? Or CircuitPython in general?

**Comment by dhalbert** [comment] 2018-10-03 20:41
> Do you mean you've seen this issue in Mu when run alongside those applications? Or CircuitPython in general?

There are problems with CircuitPython and/or the UF2 bootloader mock disk. Either the UF2 `...BOOT` drive does not appear, or `CIRCUITPY` does not appear, or the whole machine hangs. AIDA64 had trouble with UF2, but they were responsive, bought hardware, and believe they've fixed the problem.

**Comment by carlosperate** [comment] 2018-10-03 20:47
Oh, I see what you mean now, thanks for the clarification.

**Comment by carlosperate** [comment] 2021-12-29 02:14
It looks like this issue wasn't related to Mu and was fixed in CircuitPython a while ago, so I think we can close this one. Thanks everyone!

**Closed by carlosperate** 2021-12-29 02:14 UTC
