### ISSUE TITLE
1.1.0-beta-6 will not start on MacOS 11.6

### ISSUE THREAD

**Issue by mattpackwood** [mu-editor/mu#1847] opened 2021-10-06 18:36 UTC
### What were you trying to do?

Open Mu

### What steps did you take to trigger the issue?

Right click and pick "Open"

### What did you expect to happen?

Mu to open

### What actually happened?

The icon appears for about 2 seconds then it disappeared...

### Operating System Version

MacOS 11.6

### Mu Version

1.1.0-beta-6

### Editor Log

No log created....

**Comment by carlosperate** [comment] 2021-10-07 20:46
Is there a way to ensure or force the app to be opened with Rosetta?

**Comment by asgeirn** [comment] 2021-10-13 21:22
Had the same issue on 2020 MacBook Air M1.  There is no "Open using Rosetta" option in the "Get Info" menu.

Looking at the "Get Info" menu, there is one difference shown.

For beta 5, the type states "Application", but with beta 6, the type is stated as "Application (Intel)".

**Comment by tmontes** [comment] 2021-10-31 16:32
...I expect to have access to an Apple Silicon system later today. I hope that helps diagnosing and finding a common solution to both Apple Silicon and Intel Macs on the wide range of OS versions we want Mu to support (IIRC, as far back as 10.13 and into the just released 12).

I'll keep you posted, but feel free to ping me if you don't hear from me in while! :)

**Comment by tmontes** [comment] 2021-10-31 19:45
All,

I think I understood why the recently released 1.1.0b6 did not launch on Apple Silicon systems. I just fixed a mistake I did (ups!) a while back in `pup`, the tool we use to package Mu.

With that fix, I managed to package the latest Mu from `master` on my intel development system, running Mojave, move the DMG file to an Apple Silicon iMac running Big Sur 11.5.2 and successully launch Mu.

Expect an updated Mu release soon!

**Comment by tmontes** [comment] 2021-11-02 00:21
Short update:

* `pup` 1.0.0a14 including the above mentioned fix has just been released.
* Planning to cut an updated beta release within one/two weeks, per earlier cross-dev agreement.

Stay tuned!

**Comment by tmontes** [comment] 2021-11-04 00:58
All,

In exploring other topics, I myself packaged Mu Editor 1.1.0b6 (actually with a few minor changes from it) -- given that it was packaged with `pup` 1.0.0a14, it should work on Apple Silicon systems.

Published here: https://github.com/tmontes/mu/releases/tag/dev-cc6e66aabd3833a27e0178d5f9409c56ce0a22ab

Even though this is not an official release, it should at least demonstrate that our tooling is back in shape WRT supporting Apple Silicon users like you.

If anyone can test it out and let me know if it launches, I'd be thankful.

**Comment by odaki** [comment] 2021-11-04 14:21
Hi, @tmontes
Thanks for the fix.
Your package seems to be working as intended in my environment.
I am using an M1 Mac mini.

I have tried running it from the command line as well as from the GUI, but I seem to be getting Qt warnings when running it from the command line.
```
% /Applications/Mu\ Editor.app/Contents/MacOS/Mu\ Editor 
qt.qpa.drawing: Layer-backing cannot be explicitly controlled on 10.14 when built against the 10.14 SDK
```

**Comment by tmontes** [comment] 2021-11-04 23:23
Thanks for the feedback @odaki.

Not being familiar with Qt's inner workings, I have no idea of the implications of such message: hopefully things "just work"! :)

Keep in mind, though, that the official Mu macOS packages are packaged on 10.15 whereas the one I shared was packaged on 10.14 -- so there's something in the message that seems to make sense.

Let's keep this issue open until the next Mu release, at least, confirming that it indeed works on Apple Silicon hardware.

**Comment by carlosperate** [comment] 2021-12-17 22:32
`pup` v1.0.0a14 has been released, which has been tested as resolving this issue,  and the Mu build system always installs the latest version. So I think we can close this issue as resolved, in order to help us cross left over tasks in preparation for the next release.

Thanks everyone for all your help getting this resolved, and of course thanks @tmontes for updating `pup` with the fix!

**Closed by carlosperate** 2021-12-17 22:32 UTC
Labels: packaging, OS: macOS
