### ISSUE TITLE
Dark Themes no more readable on macOS Mojave beta

### ISSUE THREAD

**Issue by sstaub** [mu-editor/mu#552] opened 2018-07-12 19:24 UTC
b17, MacBook Pro15'' 10.14 Beta (18A326h) Mojave
The dark themes are no more readable on macOS Mojave Beta.
This happens on the both modes of Mojave.
<img width="288" alt="screenshot" src="https://user-images.githubusercontent.com/6450325/42654717-e0fb70d8-8619-11e8-86ef-f538617c6fb7.png">
<img width="302" alt="screenshot-1" src="https://user-images.githubusercontent.com/6450325/42654720-e37e7620-8619-11e8-812f-bca887c7a01c.png">

**Comment by ZanderBrown** [comment] 2018-07-12 19:57
Ha! Saw this earlier when someone tried it out, didn't really get a chance to investigate.

Especially when Mojave is in beta it's hard to say if this is a bug with macOS, Qt or ourselves.

@carlosperate how do they look on your mac?

**Comment by sstaub** [comment] 2018-07-12 20:08
It seems it is an macOS Mojave problem, the new dark mode is more alpha than beta.

**Comment by ZanderBrown** [comment] 2018-07-13 07:41
> My macbook crashes enough as it is (probably a hardware issue though), so I wasn't too eager to install a beta OS. HS has been fine.

(Sorry I did mean non-Beta)

**Comment by sstaub** [comment] 2018-07-13 08:03
The mu normal mode is ok, only the dark mu themes are the problem, independently of the mode of mojave.

**Comment by ZanderBrown** [comment] 2018-07-13 08:39
So just to be clear: This happens with the Mojave light theme?

**Comment by sstaub** [comment] 2018-07-13 09:07
Yes, with light and dark theme.

**Comment by stestagg** [comment] 2018-07-17 23:07
I'm seeing this too, in Mojave with both OSX light and dark theme.

For some reason, it's caused by loading/using the font from a QFontDatabase.

I've got Source Code pro installed in my system, and running mu 1.0rc unmodified shows:
<img width="932" alt="screenshot 2018-07-17 at 23 57 54" src="https://user-images.githubusercontent.com/704526/42850116-27737e90-8a1e-11e8-968a-b66047b173df.png">
<img width="932" alt="screenshot 2018-07-17 at 23 57 56" src="https://user-images.githubusercontent.com/704526/42850119-293491a6-8a1e-11e8-8f28-959db7183a26.png">

Note, all text is black, just the background color changes.

But commenting out line 67 of themes.py:
```cls._DATABASE.addApplicationFontFromData(font_data)```
causes mu to use the system installed (identical) version of Source code pro, and the text colours immediately return:

<img width="932" alt="screenshot 2018-07-18 at 00 01 33" src="https://user-images.githubusercontent.com/704526/42850175-5b5f1cd2-8a1e-11e8-9cea-0904515fa4f1.png">
<img width="932" alt="screenshot 2018-07-18 at 00 06 57" src="https://user-images.githubusercontent.com/704526/42850230-85116b02-8a1e-11e8-95e8-309be78fcfff.png">

I've dug into various things but haven't been able to get to the bottom of why using QFontDatabase loaded fonts causes this

**Comment by ntoll** [comment] 2018-07-18 12:02
OK... @stestagg, what do you suggest as a work around..? Some sort of bodge to check the platform and version..?

**Comment by ntoll** [comment] 2018-07-18 13:15
@stestagg is this something you can do/test/check? I'm currently up to my eyes with Windows signing "fun" and don't have access to a Mac.

**Comment by stestagg** [comment] 2018-07-18 13:59
Yeah. I’m out tonight but can take a look tomorrow.

Steve

**Comment by ntoll** [comment] 2018-07-18 14:54
OK... no pressure, but just so I can manage my day tomorrow, when might this be done? My aim is to have the final builds done tomorrow so I can test all the things ready for an "event free" Friday release. ;-)

**Comment by stestagg** [comment] 2018-07-18 17:12
I’ll see what I can do tonight, but I have to do a long day at work
tomorrow so that probably won’t help you much :)

I don’t think it can be that hard to do, and I e got access to OS X 11 and
12 so tonight should be reasonable

**Comment by ntoll** [comment] 2018-07-19 09:18
@stestagg you're a star! Thank you. I check / merge now.

**Comment by ntoll** [comment] 2018-07-19 15:30
Fixed by #567

**Closed by ntoll** 2018-07-19 15:30 UTC
