### ISSUE TITLE
temperature() freezes with no output and no error

### ISSUE THREAD

**Issue by frenchfaso** [mu-editor/mu#521] opened 2018-07-01 15:22 UTC
I'm not sure if this is the right place to signal this bug, it's probably a microbit-micropython bug..
when trying  to get the temperature reading, everything freezes with no error.

This is the output of os.uname() after flashing from mu:
> (sysname='microbit', nodename='microbit', release='1.0', version='micro:bit v1.0-c8c4db8 on 2017-9-27; MicroPython v1.9.2-34-gd64154c73 on 2017-09-01', machine='micro:bit with nRF51822')

with the online python editor everything works as expected, in that case the output of os.uname() is:

> (sysname='microbit', nodename='microbit', release='1.0', version='v1.7-9-gbe020eb on 2016-04-18', machine='micro:bit with nRF51822')

**Comment by ntoll** [comment] 2018-07-01 16:50
@frenchfaso are you using the latest version of Mu..? By the looks of the output, I think there's a more recent build of MicroPython in beta.16. Try the latest version, and if the problem is still there, please do let us know.

Thanks for taking the time to report this! ;-)

**Comment by carlosperate** [comment] 2018-07-02 09:11
This was an issue with an older version of MicroPython (https://github.com/bbcmicrobit/micropython/issues/481). As Nicholas has suggested, if you use the newest version of Mu it should be fixed.

**Comment by frenchfaso** [comment] 2018-07-02 13:54
Thanks for the quick reply, I'm using Mu 1 Beta 15 on raspbian, how can I update it to the latest version on the Pi3?
Thanks again for your help!

**Comment by ntoll** [comment] 2018-07-02 13:57
I'm afraid you'll just have to wait for Raspberry Pi to update things in Raspbian (something beyond our control, since it's up to them). They did mention they'll try to package 1.0.final when it's out in about a fortnight or so.

Sorry. :-(

**Comment by frenchfaso** [comment] 2018-07-07 12:35
Thank you for the response!
I'll report back as soon as Raspbian updates the Mu editor.

**Closed as completed** 2018-09-09 09:25 UTC
