### ISSUE TITLE
Initial run mode oddness

### ISSUE THREAD

**Issue by ZanderBrown** [mu-editor/mu#498] opened 2018-06-21 15:44 UTC
We now detect connected micro:bits and offer to switch to the relevant mode which is great!

However when we are on the initial run this leads to an interesting scenario where the mode selector pops up followed by the "would you like to switch". Interacting with the switch message goes roughly as expected but the mode switcher remains open.

All things considered this seems to be handled quite well but is a bit odd for users

**Comment by ZanderBrown** [comment] 2018-07-06 08:50
Running against master:
![screenshot from 2018-07-06 09-32-28](https://user-images.githubusercontent.com/17074021/42369366-a2047fb8-8101-11e8-8279-2cf64ca116a9.png)

Running against #525:
![screenshot from 2018-07-06 09-31-01](https://user-images.githubusercontent.com/17074021/42369365-a1beef8e-8101-11e8-8e24-750ca929df64.png)

Only change introduced is that the mode selector can't disappear behind the main window, in both branches only the mode switched accepts input. (The darkened area is a result of the WM knowing the modal relationship)

Also observed that the switch message can appear on top of the splash screen

**Comment by carlosperate** [comment] 2018-07-06 10:56
> the switch message can appear on top of the splash screen

I was just wondering if I opened a ticket for this one already, I don't think I did.
In my case, with the current Mu, the switch message appears behind the splash screen, but doesn't allow me to click on the spalsh screen to dismiss it, so I have to wait until the time-out removes it.

**Comment by ntoll** [comment] 2018-07-07 21:10
Heh... I keep seeing this too and it's on my "to fix in beta.17" list. I'll be all over this tomorrow.

**Comment by tmontes** [comment] 2019-06-01 11:11
I wanted to test this to verify what the current state of affairs would be, but I just can't seem to find my micro:bit! (why is it so micro? if it was bigger, I'm certain it would be easier to find) :)

Given how old the issue is and the note by @ntoll regarding an upcoming fix, can we say this issue is indeed fixed?

Context: I'm trying to contribute to some "issue triaging and organisation" help understand which of the bazillion open issues actually need attention. :)

**Comment by carlosperate** [comment] 2019-06-01 12:50
> I just can't seem to find my micro:bit!

If you still can't find it you can send me your details and I'll post you one :) (my twitter DMs are open, and/or my email is my github username at gmail.com).

**Comment by tmontes** [comment] 2019-06-01 12:54
Thanks a lot for your generous offer @carlosperate. :) :) :)

I'm positive that if I put a bit of effort into the task, I'll find it. It's just that when I went for it, I couldn't find it in one of the (not so few) obvious places.

**Comment by dybber** [comment] 2020-09-05 14:50
I just checked if I could still replicate this. On my Mac, something else, but just as problematic seems to happen. 

On an initial run, with a micro:bit connected already, the mode selector pop's up, but it doesn't show the "Detected new BBC micro:bit device".

If however, I didn't connect the micro:bit before opening, and then select a mode (e.g. Python mode), then the "Detected new BBC micro:bit device" is displayed when I connect the micro:bit.

**Comment by dybber** [comment] 2020-10-06 12:09
The issue with the splash screen not being hidden on mouse click is probably due to this:

> Since the splash screen is typically displayed before the event loop has started running, it is necessary to periodically call QCoreApplication::processEvents() to receive the mouse clicks.

https://doc.qt.io/qt-5/qsplashscreen.html

**Comment by dybber** [comment] 2020-10-06 12:38
Added a fix for that part, for the rest of this issue I can't replicate it on Mac.

On the initial run, only the mode selector (and splashscreen opens). It doesn't indicate that a device is detected with a pop-up, only in the status bar.

On subsequent runs, it opens on the mode used in the last session, and a pop-up asks if the user wants to change to the appropriate mode.

**Comment by dybber** [comment] 2020-12-05 11:09
@ZanderBrown could you check with newest master whether you're still experiencing this issue?

**Comment by ZanderBrown** [comment] 2020-12-06 19:54
Don't seem to be able to reproduce the original issue anymore - simply never offers to switch

Web detection seems to cause some weirdness when relaunching with an existing session though

Also wow 2018? How'd that happen

**Comment by carlosperate** [comment] 2021-12-27 18:40
We are unable to reproduce anymore, so let's close it as "resolved", thanks everyone!

**Closed by carlosperate** 2021-12-27 18:40 UTC
Labels: modes
