### ISSUE TITLE
Change styling for matched braces

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#163] opened 2016-10-01 22:59 UTC
It's quite a useful feature, when the cursor is next to a brace and it is highlighted with the matching counterpart.

At the moment is a feature that's only noticeable in the Night theme, when the background of the braces changes to white (which seems to be the [default behaviour](http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciScintilla.html#abf85680f914ee631aa3a513ba823271f)). So we it should be set to a style visible in both themes.

The big question would probably be what type of style. Notepad++ sets a transparent box with a light border around the braces, sublime underlines them, atom underlines on a bright colour, Intellij changes both the background and font colour, etc; so there doesn't seem to be any common standard for this feature. Any ideas?

**Comment by jezdean** [comment] 2016-10-07 11:26
Awesome idea. I can't really say which would be best from an educational perspective. I'd perhaps even say any. The solid dark borders around matching braces is also nice.

Whatever is decided, something different to the style in #164 would be important.

**Comment by carlosperate** [comment] 2016-10-07 11:50
I'll see if this weekend I can prepare a couple of gifs showing different effects, it should make the decision a bit easier.

**Comment by carlosperate** [comment] 2016-10-09 20:50
I found some time today to make this:

![underline](https://cloud.githubusercontent.com/assets/4189262/19223542/4146d5e4-8e6a-11e6-8969-0ecde106e267.gif)

![box](https://cloud.githubusercontent.com/assets/4189262/19223541/41450976-8e6a-11e6-953d-af6120f3a691.gif)

![background](https://cloud.githubusercontent.com/assets/4189262/19223539/412558e2-8e6a-11e6-9813-3e34f77b7771.gif)

![foreground_background](https://cloud.githubusercontent.com/assets/4189262/19223540/4144dc44-8e6a-11e6-9ac3-4b999066802e.gif)

**Comment by ZanderBrown** [comment] 2016-10-09 21:56
I like the look of the last one.

**Comment by carlosperate** [comment] 2016-10-10 17:24
One possible concern is how distracting this highlight could be when using the editor. The box and underline, which are more subtle that the rest, don't really look at that good with the brackets, as it seems to cut through the lower portion of the character.

I personally like the font colour change a bit more than the last one, as it doesn't get too much in the way, yet it is still visible if you look for it. The last one does make it a more clear, so I guess it depends what the general goal of the feature might be (to instruct? to subtly aid? something else?).

**Comment by ZanderBrown** [comment] 2016-10-11 07:56
Very true. the font changing is good too but I think it might be a little non obtrusive and could be unnoticeable

**Comment by jezdean** [comment] 2016-10-11 22:34
I really like the final one where it also highlights the matching parenthesis. You don't _really_ need the colour change as you can see clearly what the problem is without it.

Really awesome.

**Comment by carlosperate** [comment] 2016-10-11 23:06
One thing to keep in mind is that if #164 is implemented it will most likely use the grey square background, so we need to be conscious about having the same visual feedback for a similar (but not the same) feature.

**Comment by ZanderBrown** [comment] 2016-10-12 08:48
I think grey square is the clearest way to do this and then this and #164 + any others will have similar feedback

**Comment by ntoll** [comment] 2018-06-04 15:31
This has been fixed/updated what feels like millions of years ago. Closing... ;-)

**Closed by ntoll** 2018-06-04 15:31 UTC
