### ISSUE TITLE
print Chinese char in jupyter repl work well and could work when run a py with run button

### ISSUE THREAD

**Issue by yonghuming** [mu-editor/mu#401] opened 2018-03-22 08:14 UTC
![image](https://user-images.githubusercontent.com/435079/37758673-fe0b2424-2deb-11e8-87a4-c21bfae38689.png)

**Comment by ntoll** [comment] 2018-03-22 08:17
Are you using the latest version? I fixed this yesterday! :-)

**Comment by ntoll** [comment] 2018-03-22 08:18
See latest builds here: http://mu-builds.s3-website.eu-west-2.amazonaws.com/?prefix=windows/

**Comment by tjguk** [comment] 2018-03-22 08:20
Is it possible that, because we don't write the encoding cookie until we save (and then reload) that Jupyter's complaining? If so, we could (a) add to the new file; or (b) reload when saving so we get it in place

**Comment by yonghuming** [comment] 2018-03-22 09:41
@ntoll i use windows 10 64bit and when i print chinese it will exit immediately

**Comment by ntoll** [comment] 2018-03-22 09:43
Please confirm that you are using the *latest* version of Mu: https://s3-eu-west-2.amazonaws.com/mu-builds/windows/mu_2018-03-21_18_47_master_5ef9518_64bit.exe

**Comment by yonghuming** [comment] 2018-03-22 09:51
yes i am sure,

**Comment by yonghuming** [comment] 2018-03-22 09:51
# windows 10

**Comment by ntoll** [comment] 2018-03-22 09:58
OK... so I've managed to re-create a problem. The latest build of Mu fixes your original problem @yonghuming, however, I now see a new problem when running this on Windows (NOTE: it works fine on Linux and OSX -- I've just checked). See the attached screenie... @tjguk it looks like a Windows specific problem relating to `charmap`.  Any ideas..?

![screenshot 2](https://user-images.githubusercontent.com/37602/37763598-7655266c-2db7-11e8-8493-8fb7aecd6d13.png)

NB: I'm using the latest build (referenced in previous comment) on Windows 10 64bit, just like @yonghuming. The code I was running:

```
print("你好")
```

**Comment by ntoll** [comment] 2018-03-22 10:00
To recreate, copy the `print("你好")` code into a file and run it. Works fine on Linux/OSX.

**Comment by yonghuming** [comment] 2018-03-22 11:04
bot newest 32 and 64bit mu could not run

**Comment by yonghuming** [comment] 2018-03-22 11:30
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
i have tried but notwork



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    On 3/22/2018 17:59，Nicholas Tollervey<notifications@github.com> wrote： 


OK... so I've managed to re-create a problem. The latest build of Mu fixes your original problem @yonghuming, however, I now see a new problem when running this on Windows (NOTE: it works fine on Linux and OSX -- I've just checked). See the attached screenie... @tjguk it looks like a Windows specific problem relating to charmap.  Any ideas..?

NB: I'm using the latest build (referenced in previous comment) on Windows 10 64bit, just like @yonghuming. The code I was running:
print("你好")

**Comment by tjguk** [comment] 2018-03-22 11:47
I'll try to take a look later today unless someone gets there first.

**Comment by ntoll** [comment] 2018-03-22 14:40
I won't be able to look at this, so please knock yourself out @tjguk :-)

**Comment by ntoll** [comment] 2018-04-13 19:13
@tjguk any luck with this..?

**Comment by tjguk** [comment] 2018-05-20 10:44
just starting to look at this again. To help me and anyone else trying to reproduce, this code snippet will trigger the error:

`print("\u4f60\u597d")`

**Comment by tjguk** [comment] 2018-06-06 13:14
@yonghuming I believe that this was fixed when @ntoll merged #471. Could you try again with a dev build / git HEAD please?

**Comment by ntoll** [comment] 2018-06-13 15:20
I've checked this on my Windows10 machine and it appears to work.

**Closed by ntoll** 2018-06-13 15:20 UTC
