### ISSUE TITLE
Missing OK and Cancel buttons in select mode dialog

### ISSUE THREAD

**Issue by kamar535** [mu-editor/mu#297] opened 2017-11-11 15:43 UTC
As a follow-up to #278 I'm testing on the head of the master branch: 45694343b37ebfd7c25317811fa6a5d5292dfacb. In the window asking me to select a mode there is no OK or Cancel buttons. 

![screen shot 2017-11-07 at 16 47 10](https://user-images.githubusercontent.com/8029215/32502623-81d51d58-c3db-11e7-9bc3-481e185bc60e.png)

Changing the size of the settings window doesn't make the Ok and Cancel buttons appear.

I got these errors in the terminal when running Mu. 

```
(mu) $ python run.py
Logging to /home/kamar535/.cache/mu/log/mu.log
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
(mu) $
```

Here is the [mu.log](https://github.com/mu-editor/mu/files/1453743/mu.log)

**Comment by carlosperate** [comment] 2017-11-16 19:20
Thanks for opening the new issue @kamar535.

I assume you can still select one of the options by pressing the "Enter" key on your keyboard, or does that not work either?

**Comment by BravoDelta151** [comment] 2017-12-01 00:01
I ran into the same issue.  It was caused by having installed older PyQt libraries while testing another project.  I resolved the issue by removing PyQt and then reinstalling mu-editor with --upgrade option.  Note that I also removed QScintilla and qtconsole as well so it is possible they were at fault.
To remove:
pip uninstall PyQt5
Then:
pip install mu-editor --upgrade

**Comment by ntoll** [comment] 2017-12-01 08:29
Hi @BravoDelta151 

Awesome investigation of the fix! I'll add this to the README / documentation. Hurrah!

**Comment by kamar535** [comment] 2017-12-05 12:36
@carlosperate Pressing Enter doesn't work to select one of the options. I will now try the method described by @BravoDelta151 .

**Comment by kamar535** [comment] 2017-12-05 12:59
I can confirm that removing `PyQt5` and reinstalling Mu with the `--upgrade`options solved this issue. 

```
(mu) $ pip uninstall PyQt5
(mu) $ pip install mu-editor --upgrade
(mu) $ python3 run.py
```

<img width="613" alt="screen shot 2017-12-05 at 13 57 44" src="https://user-images.githubusercontent.com/8029215/33608266-50597f90-d9c4-11e7-9160-09a355e89805.png">

**Comment by carlosperate** [comment] 2017-12-05 14:44
Glad you got it working, and thanks @BravoDelta151 for identifying the issue!
Might be a bit late now, but do you know which version of PyQt5 was producing the issue?

**Comment by ZanderBrown** [comment] 2018-01-09 22:24
Just experience the same issue on Fedora 27, resolved with
```
$ pip3 uninstall PyQt5
$ pip3 install --user mu-editor --upgrade
```
Which also cleared up some other Qt internal issues and improved native integration (open dialogue ext)

**Comment by ntoll** [comment] 2018-03-21 18:22
Closing since this is a Qt upgrade related problem.

**Closed by ntoll** 2018-03-21 18:22 UTC
