### ISSUE TITLE
Microbit throws error on OSX

### ISSUE THREAD

**Issue by jessingrass** [mu-editor/mu#146] opened 2016-09-10 15:11 UTC
Repro steps:
1. Attach new microbit
2. download latest build (2016-08-25) of mu
3. open build
4. print('Hello, world!)
5. Flash to microbit

Expected Behavior: Hello, world!  flashes to the microbit
Actual Behavior: microbit shows as "discharged" and does not display the code
![screen shot 2016-09-10 at 10 48 27 am](https://cloud.githubusercontent.com/assets/1976801/18411537/3c649bfe-7747-11e6-8ee4-d4c58af9c0c2.png)

**Comment by ntoll** [comment] 2016-09-11 07:26
Hi @jessingrass, thanks for the feedback.

This is expected behaviour but Mu needs to signal this so people don't feel worried that something has gone wrong.

Essentially, what's happening is that the micro:bit is designed to restart once the process of flashing the device has completed. As I'm sure you know, restarting looks like unplugging and plugging in again to the "host" computer to which the device is attached. If that computer is running OSX you get the warning you see in the screenshot you attached.

Any suggestions for how to tell people this is expected..?

**Comment by jessingrass** [comment] 2016-09-12 15:05
Will work on a suggestion for wording. The bigger problem I have is that the "Hello, world!" message is NOT scrolling to the microbit. The orange light flashes indicating that something is happening, but then nothing happens on the LED screen.

**Comment by ntoll** [comment] 2016-09-12 15:16
Can you connect to the device with the REPL in Mu?

**Comment by ntoll** [comment] 2016-09-12 15:17
I see the problem... you're shouldn't `print("Hello, world!")` but `display.scroll('Hello, World!')` ;-)

See: https://microbit-micropython.readthedocs.io/en/latest/tutorials/hello.html

**Comment by jessingrass** [comment] 2016-09-12 15:18
I'm an idiot. Thanks =)

**Comment by jessingrass** [comment] 2016-09-12 15:20
As far as the messaging, maybe just tell people 
"OSX Users: if you get a 'disk not ejected properly' message, don't panic! Simply do x, y, z..."    or
"OSX Users: if you get a 'disk not ejected properly' message, don't panic! This is how mu interacts with OSX..."

**Comment by ntoll** [comment] 2018-06-04 15:15
Closing since this issue was resolved.

**Closed by ntoll** 2018-06-04 15:15 UTC
