### ISSUE TITLE
MU is "sticky"

### ISSUE THREAD

**Issue by KarlD1239** [mu-editor/mu#472] opened 2018-05-24 14:20 UTC
I have two Adafruit Feather MO Express boards with the same programs in them.  Here is what I'm experiencing:

I've noticed something else happening that might be causing problems, this with the MU editor.

I had one of the units connected and make a change in the code, like when I added the line changing the baud rate. I ran the code to check for problems and there were none so I quit the editor and ejected that unit and disconnected it from the USB port.

I then connected the other unit and opened the editor and saw that the program in that unit had the change in it without any editing by me.

I'm doing all of this on a Surface Pro 4 Windows 10

Thoughts?

**Comment by ntoll** [comment] 2018-06-04 20:42
My guess is perhaps your OS (Windows) is caching values from the filesystem and assumes they're the same thing (when in fact they're different boards with the same name/look from the PoV of the OS). Closing since I can't reproduce (I'm working on Linux -- hence my suspicion of Windows).

**Closed by ntoll** 2018-06-04 20:42 UTC
