### ISSUE TITLE
mu crashes when switching to file upload mode when micro:bit displaying error message

### ISSUE THREAD

**Issue by fizban99** [mu-editor/mu#252] opened 2017-02-25 09:51 UTC
If the micro:bit is displaying an error message, if I try to switch to file upload mode in mu, mu exits without showing any error.

**Comment by ZanderBrown** [comment] 2017-02-25 09:58
Duplicate of #242 and I believe it's been mentioned elsewhere as well

**Comment by carlosperate** [comment] 2017-11-03 16:59
Closing this one as we have https://github.com/mu-editor/mu/issues/242 already, but thanks for the report @fizban99.

**Closed by carlosperate** 2017-11-03 16:59 UTC
